# Generated by Django 5.2.1 on 2025-07-20 20:19

import channle.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channle', '0002_channel_channel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='channel_id',
            field=models.CharField(max_length=150, unique=True, validators=[channle.models.validate_channel_id_with_special_characters]),
        ),
    ]
