# Generated by Django 5.2.1 on 2025-07-14 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_managment', '0002_useraccount_groups_useraccount_is_superuser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
    ]
