# Generated by Django 5.2.1 on 2025-08-20 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_managment', '0003_alter_useraccount_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useravatar',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
